{"name": "Тест авторизации с неверным паролем", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('user_data', <FixtureRequest for <Function test_login_user_incorrect_password_error>>)", "trace": "file C:\\Users\\Daniil\\PycharmProjects\\Diplom\\Diplom_2\\tests\\test_login_user.py, line 23\n      @allure.title('Тест авторизации с неверным паролем')\n      def test_login_user_incorrect_password_error(self, user_data):\nE       fixture 'user_data' not found\n>       available fixtures: _session_faker, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, faker, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, registered_user_return_log_pass, registered_user_return_response, registered_user_return_token, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\Daniil\\PycharmProjects\\Diplom\\Diplom_2\\tests\\test_login_user.py:23"}, "start": 1709682708231, "stop": 1709682708231, "uuid": "a7851a6b-ad6e-415f-981b-2112d9dff213", "historyId": "82faacddf25850eefd1dfd8276f25d32", "testCaseId": "82faacddf25850eefd1dfd8276f25d32", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_incorrect_password_error", "labels": [{"name": "feature", "value": "Проверяем авторизацию пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-AQ71LTK"}, {"name": "thread", "value": "21816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}