{"name": "Тест авторизации с неверным паролем", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "self = <allure_commons._allure.fixture object at 0x000002D0968B1040>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\nvenv\\lib\\site-packages\\allure_commons\\_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @pytest.fixture\n    def user_data():\n        payload = helpers.payload\n        response = requests.post(EndpointsUrl.LOGIN_USER, data=payload)\n    \n        yield payload\n>       token = response.json()['accessToken']\nE       KeyError: 'accessToken'\n\nconftest.py:23: KeyError"}, "start": 1709681638860, "stop": 1709681639113, "uuid": "ada85378-4f6c-48cb-b563-3643c0dad15a", "historyId": "82faacddf25850eefd1dfd8276f25d32", "testCaseId": "82faacddf25850eefd1dfd8276f25d32", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_incorrect_password_error", "labels": [{"name": "feature", "value": "Проверяем авторизацию пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-AQ71LTK"}, {"name": "thread", "value": "18908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}